# Generated by Django 4.2.2 on 2023-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorsystem',
            name='num_floors',
            field=models.IntegerField(default=10),
        ),
    ]
