# Generated by Django 4.2.2 on 2023-06-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
